integration_name: com.newrelic.varnish

instances:
  - name: varnish_all
    command: all_data
    arguments:
      params_config_file: /etc/default/varnish.params
      instance_name: TestVarnishInstance
    labels:
      env: production
      role: varnish